export interface StaticCompany {
  id: number;
  name: string;
  source: string;
  logo: string;
}

export const STATIC_COMPANIES: StaticCompany[] = [
  { id: 1,  name: "Nice",                   source: "greenhouse", logo: "/logos/nice.png" },
  { id: 2,  name: "RazorPay",               source: "greenhouse", logo: "/logos/razorpay.png" },
  { id: 3,  name: "Stripe",                 source: "greenhouse", logo: "/logos/stripe.png" },
  { id: 4,  name: "Toast",                  source: "greenhouse", logo: "/logos/toast.png" },
  { id: 5,  name: "Rubrik",                 source: "greenhouse", logo: "/logos/rubrik.png" },
  { id: 6,  name: "Databricks",             source: "greenhouse", logo: "/logos/databricks.png" },
  { id: 7,  name: "Coinbase",               source: "greenhouse", logo: "/logos/coinbase.png" },
  { id: 8,  name: "MongoDB",                source: "greenhouse", logo: "/logos/mongodb.png" },
  { id: 9,  name: "Airbnb",                 source: "greenhouse", logo: "/logos/airbnb.png" },
  { id: 10, name: "The Trade Desk",         source: "greenhouse", logo: "/logos/the-trade-desk.png" },
  { id: 11, name: "Tower Research Capital", source: "greenhouse", logo: "/logos/tower-research-capital.png" },
  { id: 12, name: "Hackerrank",             source: "greenhouse", logo: "/logos/hackerrank.png" },
  { id: 13, name: "Cloudflare",             source: "greenhouse", logo: "/logos/cloudflare.png" },
  { id: 14, name: "Diligent Corporation",   source: "greenhouse", logo: "/logos/diligent-corporation.png" },
  { id: 15, name: "Altium",                 source: "greenhouse", logo: "/logos/altium.png" },
  { id: 16, name: "Coursera",               source: "greenhouse", logo: "/logos/coursera.png" },
  { id: 17, name: "Tekion",                 source: "greenhouse", logo: "/logos/tekion.png" },
  { id: 18, name: "Flexport",               source: "greenhouse", logo: "/logos/flexport.png" },
  { id: 19, name: "New Relic",              source: "greenhouse", logo: "/logos/new-relic.png" },
  { id: 20, name: "CommerceIQ",             source: "greenhouse", logo: "/logos/commerceiq.png" },
  { id: 22, name: "Yugabyte",               source: "greenhouse", logo: "/logos/yugabyte.png" },
  { id: 23, name: "Postman",                source: "greenhouse", logo: "/logos/postman.png" },
  { id: 24, name: "Rockstar Games",         source: "greenhouse", logo: "/logos/rockstar-games.png" },
  { id: 25, name: "FamPay",                 source: "lever",      logo: "/logos/fampay.png" },
  { id: 26, name: "Netomi",                 source: "lever",      logo: "/logos/netomi.png" },
  { id: 27, name: "Mindtickle",             source: "lever",      logo: "/logos/mindtickle.png" },
  { id: 28, name: "Paytm",                  source: "lever",      logo: "/logos/paytm.png" },
  { id: 29, name: "Upstox",                 source: "lever",      logo: "/logos/upstox.png" },
  { id: 30, name: "ION",                    source: "lever",      logo: "/logos/ion.png" },
  { id: 31, name: "pattern",                source: "lever",      logo: "/logos/pattern.png" },
  { id: 32, name: "SAFE",                   source: "lever",      logo: "/logos/safe.png" },
  { id: 33, name: "Brillio",                source: "lever",      logo: "/logos/brillio.png" },
  { id: 34, name: "Sprinto",                source: "lever",      logo: "/logos/sprinto.png" },
  { id: 35, name: "Zeta",                   source: "lever",      logo: "/logos/zeta.png" },
  { id: 36, name: "Skypoint",               source: "lever",      logo: "/logos/skypoint.png" },
  { id: 37, name: "Dozee",                  source: "lever",      logo: "/logos/dozee.png" },
  { id: 38, name: "CRED",                   source: "lever",      logo: "/logos/cred.png" },
  { id: 39, name: "Slack",                  source: "workday",    logo: "/logos/slack.png" },
  { id: 40, name: "Thomson Reuters",        source: "workday",    logo: "/logos/thomson-reuters.png" },
  { id: 41, name: "Nvidia",                 source: "workday",    logo: "/logos/nvidia.png" },
  { id: 42, name: "Adobe",                  source: "workday",    logo: "/logos/adobe.png" },
  { id: 43, name: "Salesforce",             source: "workday",    logo: "/logos/salesforce.png" },
  { id: 44, name: "Mastercard",             source: "workday",    logo: "/logos/mastercard.png" },
  { id: 45, name: "HP",                     source: "workday",    logo: "/logos/hp.png" },
  { id: 46, name: "Dell",                   source: "workday",    logo: "/logos/dell.png" },
  { id: 47, name: "Walmart",                source: "workday",    logo: "/logos/walmart.png" },
  { id: 48, name: "Target",                 source: "workday",    logo: "/logos/target.png" },
  { id: 49, name: "FedEx",                  source: "workday",    logo: "/logos/fedex.png" },
  { id: 50, name: "Philips",                source: "workday",    logo: "/logos/philips.png" },
  { id: 51, name: "Netflix",                source: "workday",    logo: "/logos/netflix.png" },
  { id: 52, name: "Autodesk",               source: "workday",    logo: "/logos/autodesk.png" },
  { id: 53, name: "Morgan Stanley",         source: "eightfold",  logo: "/logos/morgan-stanley.jpeg" },
  { id: 54, name: "PTC",                    source: "eightfold",  logo: "/logos/ptc.png" },
  { id: 55, name: "Zebra",                  source: "eightfold",  logo: "/logos/zebra.jpg" },
  { id: 56, name: "Dropbox",               source: "greenhouse", logo: "/logos/dropbox.svg" },
  { id: 57, name: "Pinterest",             source: "greenhouse", logo: "/logos/pinterest.png" },
  { id: 58, name: "Robinhood",             source: "greenhouse", logo: "/logos/robinhood.svg" },
  { id: 59, name: "Figma",                 source: "greenhouse", logo: "/logos/figma.svg" },
  { id: 60, name: "Discord",               source: "greenhouse", logo: "/logos/discord.svg" },
  { id: 61, name: "Duolingo",              source: "greenhouse", logo: "/logos/duolingo.svg" },
  { id: 62, name: "Gusto",                 source: "greenhouse", logo: "/logos/gusto.svg" },
  { id: 63, name: "Cockroach Labs",        source: "greenhouse", logo: "/logos/cockroach-labs.svg" },
  { id: 64, name: "Vercel",                source: "greenhouse", logo: "/logos/vercel.svg" },
  { id: 65, name: "Anduril",               source: "greenhouse", logo: "/logos/anduril.svg" },
  { id: 66, name: "Mercury",               source: "greenhouse", logo: "/logos/mercury.png" },
  { id: 67, name: "Navan",                 source: "greenhouse", logo: "/logos/navan.png" },
  { id: 68, name: "Webflow",               source: "greenhouse", logo: "/logos/webflow.svg" },
  { id: 69, name: "Samsara",               source: "greenhouse", logo: "/logos/samsara.svg" },
  { id: 70, name: "Brex",                  source: "greenhouse", logo: "/logos/brex.svg" },
  { id: 71, name: "Scale Ai",              source: "greenhouse", logo: "/logos/scale-ai.svg" },
  { id: 72, name: "Reddit",                source: "greenhouse", logo: "/logos/reddit.svg" },
  { id: 73, name: "Glean",                 source: "greenhouse", logo: "/logos/glean.svg" },
  { id: 74, name: "Lyft",                  source: "greenhouse", logo: "/logos/lyft.svg" },
  { id: 75, name: "Carta",                 source: "greenhouse",      logo: "/logos/carta.png" },
  { id: 76, name: "Airtable",              source: "greenhouse",      logo: "/logos/airtable.png" },
  { id: 77, name: "Intercom",              source: "greenhouse",      logo: "/logos/intercom.svg" },
  { id: 78, name: "Netlify",               source: "greenhouse",      logo: "/logos/netlify.svg" },
  { id: 79, name: "Amplitude",             source: "greenhouse",      logo: "/logos/amplitude.png" },
  { id: 80, name: "Contentful",            source: "greenhouse",      logo: "/logos/contentful.png" },
  { id: 81, name: "PagerDuty",             source: "greenhouse",      logo: "/logos/pagerduty.svg" },
  { id: 82, name: "Cisco",                 source: "workday",    logo: "/logos/cisco.svg" },
  { id: 83, name: "Intel",                 source: "workday",    logo: "/logos/intel.svg" },
  { id: 84, name: "Paypal",                source: "workday",    logo: "/logos/paypal.svg" },
  { id: 85, name: "Zoom",                  source: "workday",    logo: "/logos/zoom.svg" },
  { id: 86, name: "Palo Alto",    source: "workday",    logo: "/logos/palo-alto.svg" },
  { id: 87, name: "CrowdStrike",           source: "workday",    logo: "/logos/crowdstrike.svg" },
  { id: 88, name: "Accenture",             source: "workday",    logo: "/logos/accenture.svg" },
  { id: 89, name: "Genpact",               source: "workday",  logo: "/logos/genpact.png" },
  { id: 90, name: "Micron",                source: "workday",  logo: "/logos/micron.svg" },
  { id: 91, name: "Expedia Group",         source: "workday",    logo: "/logos/expedia.png" },
  { id: 92, name: "Clarivate",             source: "workday",    logo: "/logos/clarivate.png" },
  { id: 93, name: "Maersk",               source: "workday",    logo: "/logos/maersk.svg" },
  { id: 94, name: "F5",                   source: "workday",    logo: "/logos/f5.svg" },
  { id: 95, name: "CME Group",            source: "workday",    logo: "/logos/cme-group.svg" },
  { id: 96, name: "Barclays",             source: "workday",    logo: "/logos/barclays.svg" },
  { id: 97, name: "BrowserStack",         source: "workday", logo: "/logos/browserstack.png" },
  { id: 98, name: "Cigna Group",          source: "workday",    logo: "/logos/cigna.svg" },
  { id: 99, name: "Baker Hughes",         source: "workday",    logo: "/logos/baker-hughes.svg" },
  { id: 100, name: "Danaher",             source: "workday",    logo: "/logos/danaher.png" },
  { id: 101, name: "GE HealthCare",       source: "workday",    logo: "/logos/ge-healthcare.png" },
  { id: 102, name: "Augury",              source: "greenhouse", logo: "/logos/augury.svg" },
  { id: 103, name: "Nike",               source: "workday",    logo: "/logos/nike.svg" },
  { id: 104, name: "Arcesium",           source: "greenhouse", logo: "/logos/arcesium.svg" },
  { id: 105, name: "Yokogawa",           source: "workday",    logo: "/logos/yokogawa.svg" },
  { id: 106, name: "Agoda",              source: "greenhouse", logo: "/logos/agoda.jpg" },
];

/** Keyed by company name — drop-in replacement for company-logos.json imports */
export const COMPANY_LOGOS: Record<string, string> = Object.fromEntries(
  STATIC_COMPANIES.map((c) => [c.name, c.logo])
);
